# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'blog_group',
            },
        ),
        migrations.CreateModel(
            name='MemberShip',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Student')),
            ],
            options={
                'db_table': 'blog_membership',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='blog.MemberShip', to='blog.Student'),
        ),
    ]
